id: P006616
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC50
  title: བསྟན་བཅོས་མངོན་རྟོགས་རྒྱན་ཚིག་དོན་གྱི་སྒོ་ནས་བཤད་པ་བྱམས་མགོན་ཞལ་ལུང་།
  author: ''
  volumes:
    eaf452b2e8274501964cde97fcaf23d2:
      image_group_id: I2PD18743
      title: ''
      volume_number: 1
      total_pages: 252
      base_file: v001.txt
