id: I348FB54A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:19:04+00:00'
last_modified: '2022-06-08T05:39:17.882109+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC50
  title: བསྟན་བཅོས་མངོན་རྟོགས་རྒྱན་ཚིག་དོན་གྱི་སྒོ་ནས་བཤད་པ་བྱམས་མགོན་ཞལ་ལུང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    52BC:
      image_group_id: I2PD18743
      title: ''
      total_pages: 252
      order: 1
      base_file: 52BC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
